import { useState, useEffect } from 'react';
import { StyleSheet, View, Text, Pressable, Linking, ScrollView } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import Constants from 'expo-constants';
import * as Application from 'expo-application';
import { track, getDeviceId } from '@/utils/analytics';
import { PRIVACY_POLICY_URL } from '@/constants/api';

const DISCLAIMER_TEXT =
  'Roasts are generated by AI for entertainment purposes only and should not be taken seriously. ' +
  'Roast AI is designed to be fun and lighthearted. The roasts do not reflect real assessments ' +
  'of your appearance, personality, or character. Please use this app responsibly and remember ' +
  'that everything generated is fictional humor.';

export default function AboutScreen() {
  const [deviceId, setDeviceId] = useState('');
  const [disclaimerOpen, setDisclaimerOpen] = useState(false);

  const appVersion = Constants.expoConfig?.version ?? 'unknown';
  const buildNumber = Application.nativeBuildVersion;
  const versionDisplay = buildNumber ? `${appVersion} (${buildNumber})` : appVersion;

  useEffect(() => {
    track('about_viewed');
    getDeviceId().then(setDeviceId);
  }, []);

  const handleFeedback = () => {
    track('feedback_pressed');
    const body = [
      'Roast AI Feedback\n',
      `Device ID: ${deviceId}`,
      `App Version: ${versionDisplay}`,
      '\nDescribe the issue or suggestion here:\n',
    ].join('\n');
    const url = `mailto:?subject=${encodeURIComponent('Roast AI Feedback')}&body=${encodeURIComponent(body)}`;
    Linking.openURL(url);
  };

  const handlePrivacyPolicy = () => {
    track('privacy_policy_pressed');
    Linking.openURL(PRIVACY_POLICY_URL);
  };

  return (
    <LinearGradient colors={['#0f0f12', '#140c0f']} style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={styles.section}>
          <Pressable style={({ pressed }) => [styles.row, pressed && styles.rowPressed]} onPress={handleFeedback}>
            <Text style={styles.rowText}>Send Feedback</Text>
            <Text style={styles.rowChevron}>&rsaquo;</Text>
          </Pressable>

          <View style={styles.separator} />

          <Pressable style={({ pressed }) => [styles.row, pressed && styles.rowPressed]} onPress={handlePrivacyPolicy}>
            <Text style={styles.rowText}>Privacy Policy</Text>
            <Text style={styles.rowChevron}>&rsaquo;</Text>
          </Pressable>

          <View style={styles.separator} />

          <Pressable
            style={({ pressed }) => [styles.row, pressed && styles.rowPressed]}
            onPress={() => { setDisclaimerOpen(!disclaimerOpen); track('disclaimer_pressed'); }}
          >
            <Text style={styles.rowText}>Entertainment Disclaimer</Text>
            <Text style={styles.rowChevron}>{disclaimerOpen ? '\u2039' : '\u203A'}</Text>
          </Pressable>

          {disclaimerOpen && (
            <View style={styles.disclaimerBody}>
              <Text style={styles.disclaimerText}>{DISCLAIMER_TEXT}</Text>
            </View>
          )}
        </View>

        <Text style={styles.version}>Roast AI v{versionDisplay}</Text>
      </ScrollView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    paddingTop: 32,
  },
  section: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 14,
    overflow: 'hidden',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  rowPressed: {
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  rowText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  rowChevron: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 20,
    fontWeight: '600',
  },
  separator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,0.1)',
    marginLeft: 16,
  },
  disclaimerBody: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  disclaimerText: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 14,
    lineHeight: 21,
  },
  version: {
    color: 'rgba(255,255,255,0.25)',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 24,
  },
});
